[phases.setup]
nixPkgs = ["...", "nginx"]

[phases.build]
cmds = ["npm ci", "npm run build"]

[start]
cmd = "nginx -c /etc/nginx/nginx.conf -g 'daemon off;'"

[staticAssets]
root = "dist"

# Nginx config for SPA routing
